# Generated by Django 4.0.3 on 2022-04-20 09:56

import os

from django.contrib.auth import get_user_model
from django.db import migrations
from users.models import Address


def create_super_user(apps, schema_editor):
    Account = get_user_model()

    DJANGO_SU_FIRST_NAME = os.environ.get('DJANGO_SU_FIRST_NAME')
    DJANGO_SU_LAST_NAME = os.environ.get('DJANGO_SU_LAST_NAME')
    DJANGO_SU_COMPANY_NAME = os.environ.get('DJANGO_SU_COMPANY_NAME')
    DJANGO_SU_USER_TYPE = os.environ.get('DANGO_SU_USER_TYPE')
    DJANGO_SU_EMAIL = os.environ.get('DJANGO_SU_EMAIL')
    DJANGO_SU_PASSWORD = os.environ.get('DJANGO_SU_PASSWORD')

    Account.objects.create_superuser(
        first_name=DJANGO_SU_FIRST_NAME,
        last_name=DJANGO_SU_LAST_NAME,
        company_name=DJANGO_SU_COMPANY_NAME,
        email=DJANGO_SU_EMAIL,
        address=Address.objects.latest('id'),
        user_type=DJANGO_SU_USER_TYPE,
        password=DJANGO_SU_PASSWORD,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_super_user)
    ]
