# Generated by Django 4.0.3 on 2022-04-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0004_alter_horse_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
