# Generated by Django 4.0.3 on 2022-04-23 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0006_stable_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
