# Generated by Django 4.0.3 on 2022-04-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0012_remove_training_horse_alter_training_horse_bit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='training',
            field=models.ManyToManyField(through='horses.HorseTraining', to='horses.training'),
        ),
    ]
