# Generated by Django 4.0.3 on 2022-04-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0009_alter_horse_farrier_alter_horse_vet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feeding',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feeding',
            name='breakfast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feeding',
            name='dinner',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feeding',
            name='supper',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='feeding',
            name='description',
        ),
        migrations.RemoveField(
            model_name='feeding',
            name='meal',
        ),
    ]
