# Generated by Django 4.0.3 on 2022-04-27 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0010_alter_feeding_unique_together_feeding_breakfast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='raider',
            field=models.CharField(default='Add raider name', max_length=64),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.RemoveField(
            model_name='training',
            name='horse',
        ),
        migrations.AddField(
            model_name='training',
            name='horse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='horses.horse'),
        ),
        migrations.RemoveField(
            model_name='training',
            name='horse_bit',
        ),
        migrations.AddField(
            model_name='training',
            name='horse_bit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Trainings', to='horses.bitstouse'),
        ),
        migrations.AlterField(
            model_name='training',
            name='hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainer',
            field=models.CharField(default='Add trainer name', max_length=64),
        ),
    ]
