# Generated by Django 4.0.3 on 2022-04-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0013_horse_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='training',
        ),
        migrations.AddField(
            model_name='training',
            name='horse',
            field=models.ManyToManyField(through='horses.HorseTraining', to='horses.horse'),
        ),
    ]
