# Generated by Django 4.0.3 on 2022-04-28 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0014_remove_horse_training_training_horse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horsetraining',
            name='training',
        ),
        migrations.AddField(
            model_name='horsetraining',
            name='training_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='training',
            name='horse',
        ),
        migrations.AddField(
            model_name='training',
            name='horse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='horses.horsetraining'),
        ),
    ]
