# Generated by Django 4.0.3 on 2022-04-22 19:05
import os

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    Group.objects.create(name=os.environ.get('DJ_GROUP_STB_OWNERS'))
    Group.objects.create(name=os.environ.get('DJ_GROUP_VETERINARIANS'))
    Group.objects.create(name=os.environ.get('DJ_GROUP_FARRIERS'))


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            os.environ.get('DJ_GROUP_STB_OWNERS'),
            os.environ.get('DJ_GROUP_VETERINARIANS'),
            os.environ.get('DJ_GROUP_FARRIERS'),
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, revert_migration)
    ]
